# Generated by Django 4.2.13 on 2024-06-04 09:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0004_alter_friendrequest_from_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='friends',
            field=models.ManyToManyField(related_name='friends_with', through='social_app.Friendship', to=settings.AUTH_USER_MODEL),
        ),
    ]
